ARG NODE_VERSION=24.8.0-alpine
ARG NGINX_VERSION=stable-alpine

FROM node:${NODE_VERSION} AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm ci
COPY . .

ARG BACKEND_API_URL
ARG NG_GOOGLE_CLIENT_ID

RUN echo "BACKEND_API_URL=${BACKEND_API_URL}" > .env && \
    echo "NG_GOOGLE_CLIENT_ID=${NG_GOOGLE_CLIENT_ID}" >> .env

RUN npm run build

FROM nginxinc/nginx-unprivileged:${NGINX_VERSION} AS runner
USER root

COPY nginx.prod.conf /etc/nginx/nginx.prod.conf
COPY nginx.dev.conf /etc/nginx/nginx.dev.conf
COPY docker-entrypoint.sh /docker-entrypoint.sh
COPY --chown=nginx:nginx --from=builder /app/dist/*/browser /usr/share/nginx/html

RUN apk add --no-cache curl && chmod +x /docker-entrypoint.sh

USER nginx
EXPOSE 4200
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]