ARG NODE_VERSION=24.8.0-alpine
ARG NGINX_VERSION=alpine3.22
ARG USER_NAME = nginx
ARG USER_UID = 1000
ARG USER_GID = 1000
 
FROM node:${NODE_VERSION} AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm ci
COPY . .
RUN npm run build 

FROM nginxinc/nginx-unprivileged:${NGINX_VERSION} AS runner
USER nginx 
COPY nginx.conf /etc/nginx/nginx.conf
COPY --chown=nginx:nginx --from=builder /app/dist/*/browser /usr/share/nginx/html
EXPOSE 8080

USER ROOT 
RUN groupadd -g ${USER_GID} ${USER_NAME} && useradd -m -u ${USER_UID} -g ${USER_GID} -s /bin/bash ${USER_NAME}
RUN chown 755 -R ${USER_NAME}:${USER_NAME} /etc/letsencrypt && chmod 755 -R ${USER_NAME}:${USER_NAME} /etc/letsencrypt
RUN chown 755 -R ${USER_NAME}:${USER_NAME} /etc/nginx && chmod 755 -R ${USER_NAME}:${USER_NAME} /etc/nginx
USER nginx

ENTRYPOINT ["nginx", "-c", "/etc/nginx/nginx.conf"]
CMD ["-g", "daemon off;"]
