ARG NODE_VERSION=24.8.0-alpine
ARG NGINX_VERSION=alpine3.23

FROM node:${NODE_VERSION} AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm ci
COPY . .
RUN npm run build

FROM nginx:${NGINX_VERSION} AS runner
USER root

COPY nginx.conf /etc/nginx/nginx.conf
COPY --chown=nginx:nginx --from=builder /app/dist/*/browser /usr/share/nginx/html

RUN chown -R nginx:nginx /etc/nginx && \
    chmod -R 755 /etc/nginx

RUN mkdir -p /etc/letsencrypt && \
    chown -R nginx:nginx /etc/letsencrypt && \
    chmod -R 755 /etc/letsencrypt

USER nginx

EXPOSE 8080

ENTRYPOINT ["nginx", "-c", "/etc/nginx/nginx.conf"]
CMD ["-g", "daemon off;"]
