FROM mcr.microsoft.com/dotnet/sdk:10.0 AS publish
WORKDIR /src

COPY *.sln ./
COPY Backend.Api.csproj ./
COPY Database/Backend.Database.csproj ./Database/

RUN dotnet restore ./Backend.Api.csproj

COPY . .
RUN dotnet publish "Backend.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    rm -rf /var/lib/apt/lists/* && \
    curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg   

COPY --from=publish /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "Backend.Api.dll"]