# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS publish
ARG csharpProjectLocation="backend.csproj"
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./backend/
COPY ./Database/Backend.Database.csproj ./backend/Database/
COPY *.sln .
RUN dotnet restore ./backend/Backend.Api.csproj

# copy everything else and build app
COPY . ./backend/
WORKDIR /app/backend
RUN dotnet publish ./Backend.Api.csproj -c Debug -o /app/publish

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    rm -rf /var/lib/apt/lists/*

COPY --from=publish /app/publish .

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dotnet", "Backend.Api.dll"]

# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS publish
WORKDIR /src

COPY *.sln ./
COPY Backend.Api.csproj ./
COPY Database/Backend.Database.csproj ./Database/

RUN dotnet restore ./Backend.Api.csproj

COPY . .

RUN dotnet publish "Backend.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    rm -rf /var/lib/apt/lists/*

COPY --from=publish /app/publish .

EXPOSE 5000

ENTRYPOINT ["dotnet", "Backend.Api.dll"]