FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS publish
WORKDIR /src

COPY *.sln ./
COPY Backend.Api.csproj ./
COPY Database/Backend.Database.csproj ./Database/

RUN mkdir -p wwwroot/uploads
RUN mkdir -p wwwroot/uploads/audio
RUN mkdir -p wwwroot/uploads/documents
RUN mkdir -p wwwroot/uploads/images
RUN mkdir -p wwwroot/uploads/videos
RUN mkdir -p wwwroot/uploads/files

RUN dotnet restore ./Backend.Api.csproj

COPY . .
RUN dotnet publish "Backend.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine AS final
WORKDIR /app

RUN apk add --no-cache curl icu-libs

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

COPY --from=publish /app/publish .

COPY --from=publish /src/wwwroot ./wwwroot                    

EXPOSE 8080

ENTRYPOINT ["dotnet", "Backend.Api.dll"]