# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS publish
ARG csharpProjectLocation="backend.csproj"
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./backend/
COPY ./Database/Backend.Database.csproj ./backend/Database/
COPY *.sln .
RUN dotnet restore ./backend/Backend.Api.csproj

# copy everything else and build app
COPY . ./backend/
WORKDIR /app/backend
RUN dotnet publish ./Backend.Api.csproj -c Debug -o /app/publish

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dotnet", "backend.dll"]