ARG csharpProjectLocation="DevGuard.Api.csproj"

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY [$csharpProjectLocation, "."]
RUN dotnet restore
COPY . . 
RUN dotnet build "$csharpProjectLocation" -c Release -o /app/build

FROM build as publish
RUN dotnet publish "$csharpProjectLocation" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DevGuard.Api.dll"]